### GetAll
GET http://sitemainventario6to/productos

### Modificar producto
PUT http://sitemainventario6to/productos/1

{
    "codbarras":"750100000001",
    "nombre":"computadora ",
    "descripcion":"computadora de escritorio",
    "stock_actual":200,
    "stock_minimo":13,
    "precio_costo":20.00
}
### Adicionar producto
POST http://sitemainventario6to/productos/

{
    "codbarras":"750100000032",
    "nombre":"silla ",
    "descripcion":"silla de oficina",
    "stock_actual":20,
    "stock_minimo":13,
    "precio_costo":25.00,
    "cod_categoria":2,
    "cod_ubicacion":3
}